name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Toolchain
        run: swift --version
      - name: Test
        run: ./script/ci.sh

